---
spring:
  profiles: web-local
  profiles.include: web
  mvc:
    locale: ko_KR

# logging
logging:
  config: classpath:logback-spring-test.xml

# datasource
datasource:
  deliveryDispatch:
    initialize: true
    initial-size: 10
    max-total: 10
    max-idle: 10
    min-idle: 10
    max-wait-millis: 3000
    test-on-borrow: true
    validation-query: select 1
    test-while-idle: true
    min-evictable-idle-time-millis: 28700
    time-between-eviction-runs-millis: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:mysql://127.0.0.1:3306/devdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    username: devuser
#    password: devuserpw!

    url: jdbc:mysql://home.kaifalife.com:33306/devdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: devuser
    password: devuserpw!

#    url: jdbc:mysql://104.199.200.242:3306/devdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    username: devuser
#    password: devuserpw!

---
spring:
  profiles: local

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
      scheme: http
      host: localhost
      port: 8091
      maxPerRoute: 20

---
spring:
  profiles: oper

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
      scheme: http
      host: dev-api.jrgtw.com
      port: 8091
      maxPerRoute: 20

    -
      scheme: https
      host: dev-api.jrgtw.com
      port: 443
      maxPerRoute: 20

---
# Redis
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2

---
# Upload Path
api.upload.path.notice: /home/ddetest/dde-upload/notice
api.upload.path.alarm: /home/ddetest/dde-upload/alarm

---
# Web socket
websocket.localhost: 127.0.0.1:3000
#websocket.localhost: https://dev-store.cntt.co.kr

---
#cors domain
api.cors.origin: http://localhost:8091