---
spring:
  profiles: web-test
  profiles.include: web
  application.name: delivery-dispatch-mvc
  mvc:
    locale: zh_HK

# was
server:
  session:
    cookie:
      http-only: true
      secure: true

# logging
logging:
  config: classpath:logback-spring-test.xml

# datasource
datasource:
  deliveryDispatch:
    initialize: true
    initial-size: 20
    max-total: 100
    max-idle: 100
    min-idle: 20
    max-wait-millis: 3000
    test-on-borrow: true
    validation-query: select 1
    test-while-idle: true
    min-evictable-idle-time-millis: 28700
    time-between-eviction-runs-millis: 60000
    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://127.0.0.1:3306/devdb?useUnicode=true&characterEncoding=utf8
    username: devuser
    password: devuserpw!

---
spring:
  profiles: oper

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
      scheme: http
      host: dev-api.cntt.co.kr
      port: 8091
      maxPerRoute: 20

    -
      scheme: https
      host: dev-api.cntt.co.kr
      port: 443
      maxPerRoute: 20

---
# Redis
spring:
  redis:
    host: 127.0.0.1
    port: 6379

---
# Upload Path
api.upload.path.notice: /home/ddetest/dde-upload/notice
api.upload.path.alarm: /home/ddetest/dde-upload/alarm

---
# Web socket
websocket.localhost: https://dev-store.cntt.co.kr

---
#cors domain
api.cors.origin: http://dev-api.cntt.co.kr