---
spring:
  profiles: admin-connor
  profiles.include: admin
  mvc:
    locale: ko_KR

# was
server:
  session:
    cookie:
      secure: true
      http-only: true

# logging
logging:
  config: classpath:logback-spring-connor.xml

# datasource
datasource:
  deliveryDispatch:
    initialize: true
    initial-size: 10
    max-total: 10
    max-idle: 10
    min-idle: 10
    max-wait-millis: 3000
    test-on-borrow: true
    #validation-query: select 1
    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://1.255.51.183:3306/devdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: devuser
    password: devuserpw!

---
spring:
  profiles: oper

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
      scheme: http
      host: dde-api.connor.local
      port: 8091
      maxPerRoute: 20
    -
      scheme: https
      host: dde-api.connor.local
      port: 443
      maxPerRoute: 20

---
spring:
  redis:
    host: 192.168.0.8
    port: 6379

---
api.upload.path.notice: /home/connor/websites/DDE/dde-upload/notice
api.upload.path.alarm: /home/connor/websites/DDE/dde-upload/alarm

---
api.default.alarms: newAlarm.wav,assignAlarm.wav,assignedCancelAlarm.wav,completeAlarm.wav,cancelAlarm.wav
