---
spring:
  profiles: admin-hk
  profiles.include: admin
  mvc:
    locale: zh_HK

# was
server:
  session:
    cookie:
      secure: true
      http-only: true

# logging
logging:
  config: classpath:logback-spring-hk.xml

# datasource
datasource:
  deliveryDispatch:
    initialize: true
    initial-size: 10
    max-total: 10
    max-idle: 10
    min-idle: 10
    max-wait-millis: 3000
    test-on-borrow: true
    #validation-query: select 1
    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://192.168.100.73:3306/hkdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: hkuser
    password: hkuserpw!

---
spring:
  profiles: oper

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
      scheme: http
      host: ddehk-api.cntt.co.kr
      port: 8091
      maxPerRoute: 20

    -
      scheme: https
      host: ddehk-api.cntt.co.kr
      port: 443
      maxPerRoute: 20

---
spring:
  redis:
    host: 192.168.100.81
    port: 6379

---
api.upload.path.notice: /home/ddehk/dde-upload/notice
api.upload.path.alarm: /home/ddehk/dde-upload/alarm

---
api.default.alarms: newAlarm.wav,assignAlarm.wav,assignedCancelAlarm.wav,completeAlarm.wav,cancelAlarm.wav
