---
spring:
  profiles: admin-local
  profiles.include: admin
  mvc:
    locale: ko_KR

# logging
logging:
  config: classpath:logback-spring-test.xml

# datasource
datasource:
  deliveryDispatch:
    initialize: true
    initial-size: 10
    max-total: 10
    max-idle: 10
    min-idle: 10
    max-wait-millis: 3000
    test-on-borrow: true
    #validation-query: select 1
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://127.0.0.1:3306/devdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: devuser
    password: devuserpw!

#    url: jdbc:mysql://110.234.0.156:3306/twdb?useUnicode=true&characterEncoding=utf8
#    username: twuser
#    password: twuserpw!



---
spring:
  profiles: oper

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
      scheme: http
      host: dev-api.cntt.co.kr
      port: 8091
      maxPerRoute: 20

    -
      scheme: https
      host: dev-api.cntt.co.kr
      port: 443
      maxPerRoute: 20

---
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1

---
api.upload.path.notice: /home/ddetest/dde-upload/notice
api.upload.path.alarm: /home/ddetest/dde-upload/alarm

---
api.default.alarms: newAlarm.wav,assignAlarm.wav,assignedCancelAlarm.wav,completeAlarm.wav,cancelAlarm.wav
# Web socket
websocket.localhost: 127.0.0.1:3000
