---
spring:
  profiles: admin
  application.name: delivery-dispatch-admin
  mvc:
    locale: zh_TW
#    locale: zh_HK
#    locale: ko_KR
    favicon.enabled: false
  messages:
    cache-seconds: -1
    basename: classpath:/META-INF/messages/exceptions
                , classpath:/META-INF/messages/messages
    encoding: UTF-8
    #fallback-to-system-locale: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: true
  thymeleaf:
      cache : false
      prefix: classpath:/templates

management:
  context-path: /monitor

# was
server:
  port: 8181
  tomcat:
    uri-encoding: UTF-8
  jsp-servlet:
    init-parameters:
      development: true
  session:
    timeout: 3600
    cookie:
      secure: true
      http-only: true

# logging
logging:
# [DDE-TW-MAIN]
  config: classpath:logback-spring-tw.xml

# [DDE-HK-MAIN]
#  config: classpath:logback-spring-hk.xml

# datasource
datasource:
  deliveryDispatch:
    initialize: true
    initial-size: 10
    max-total: 10
    max-idle: 10
    min-idle: 10
    max-wait-millis: 3000
    test-on-borrow: true
    #validation-query: select 1
    driver-class-name: com.mysql.jdbc.Driver

#    [DDE-TW-MAIN]
    url: jdbc:mysql://dde-db.cs4wechlbmlc.ap-northeast-2.rds.amazonaws.com:3306/dde?useUnicode=true&characterEncoding=utf8
    username: nanum
    password: snaskzhf

#    [DDE-TW-TEST]
#    url: jdbc:mysql://delivery-dispatch-test-db.cktgcdnnnhc9.ap-northeast-2.rds.amazonaws.com:3306/dde?useUnicode=true&characterEncoding=utf8
#    username: nanum
#    password: snaskzhf

#    [DDE-HK-MAIN]
#    url: jdbc:mysql://192.168.100.73:3306/hkdb?useUnicode=true&characterEncoding=utf8
#    username: hkuser
#    password: hkuserpw!

# concurrent
cntt.concurrent.enable: true
cntt.concurrent.threadCount: 8

# spring security disabled
security.basic.enabled: false
management.security.enabled: false

# mail service
#cntt.mail:
#  enable : true
#  sender : Do_not_reply@burgerking.co.kr
#  imageHeader : http://delivery.burgerking.co.kr/files/mail/mail_header.gif
#  imageLock : http://delivery.burgerking.co.kr/files/mail/img_lock.gif
#  tempPasswordMailTitle : TEST
#  tempPasswordMailHtmlPath : classpath:templates/mail/tempPasswordMail.html
#  tempPasswordMailSampleHtmlPath1 : classpath:templates/mail/tempPasswordMailSample1.html
#  tempPasswordMailSampleHtmlPath2 : classpath:templates/mail/tempPasswordMailSample2.html
#  tempPasswordMailSampleHtmlPath3 : classpath:templates/mail/tempPasswordMailSample3.html

cntt:
  underConstruction:
    redirectUrl: /caution
    ignoreIps: 127.0.0.1, 0:0:0:0:0:0:0:1, 123.111.91.3
    paramAdminPw: cbody
    active: true

---
spring:
  profiles: local

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
      scheme: http
      host: localhost
      port: 8091
      maxPerRoute: 20

# Logger
cntt.monitor.enable: true
cntt.monitor.basepackage: kr.co.cntt.deliverydispatchadmin

---
spring:
  profiles: dev

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
      scheme: http
      host: localhost
      port: 8085
      maxPerRoute: 20

# Logger
cntt.monitor.enable: true
cntt.monitor.basepackage: kr.co.cntt.deliverydispatchadmin

---
spring:
  profiles: oper

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
#      [DDE-TW-MAIN]
      scheme: http
      host: ddetw-api.cntt.co.kr
      port: 8091
      maxPerRoute: 20

#      [DDE-TW-TEST]
#      scheme: http
#      host: dev-api.cntt.co.kr
#      port: 8091
#      maxPerRoute: 20

#      [DDE-HK-MAIN]
#      scheme: http
#      host: ddehk-api.cntt.co.kr
#      port: 8091
#      maxPerRoute: 20

    -
#      [DDE-TW-MAIN]
      scheme: https
      host: ddetw-api.cntt.co.kr
      port: 443
      maxPerRoute: 20

#      [DDE-TW-TEST]
#      scheme: https
#      host: dev-api.cntt.co.kr
#      port: 443
#      maxPerRoute: 20

#      [DDE-HK-MAIN]
#      scheme: https
#      host: ddehk-api.cntt.co.kr
#      port: 443
#      maxPerRoute: 20

# Logger
cntt.monitor.enable: true
cntt.monitor.basepackage: kr.co.cntt.deliverydispatchadmin

---
spring:
  redis:
#    [DDE-TW-MAIN]
    host: dde-tw-redis.dgc5ym.0001.apn2.cache.amazonaws.com
    port: 6379

#    [DDE-TW-TEST]
#    host: nanum-taiwan-redis.e6yhbk.0001.apn2.cache.amazonaws.com
#    port: 6379

#    [DDE-HK-MAIN]
#    host: 192.168.100.81
#    port: 6379

#    [DDE-KR-LOCAL]
#    host: 127.0.0.1
#    port: 6379

api.token.serviceKey : testkey
api.token.secretKey : ATE6OLdQuouPbqyZ5qt1H++taImbDhqSPw53ClPT7+k=
api.token.expiration : 6000

---
api.tracker.key: sg9h6f6rg4lo1i3s255czh31v9zxc029

---
#[DDE-TW-MAIN]
api.upload.path.notice: /home/nanum/dde-upload/notice
api.upload.path.alarm: /home/nanum/dde-upload/alarm

#[DDE-HK-MAIN]
#api.upload.path.notice: /root/dde-upload/notice
#api.upload.path.alarm: /root/dde-upload/alarm
