---
spring:
  profiles: admin-test
  profiles.include: admin
  mvc:
    locale: zh_TW

# was
server:
  session:
    cookie:
      secure: true
      http-only: true

# logging
logging:
  config: classpath:logback-spring-test.xml

# datasource
datasource:
  deliveryDispatch:
    initialize: true
    initial-size: 10
    max-total: 10
    max-idle: 10
    min-idle: 10
    max-wait-millis: 3000
    test-on-borrow: true
    #validation-query: select 1
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://10.156.32.14:3306/devdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: devuser
    password: devuserpw!

---
spring:
  profiles: oper

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
      scheme: http
      host: dev-api.jrgtw.com
      port: 8091
      maxPerRoute: 20
    -
      scheme: https
      host: dev-api.jrgtw.com
      port: 443
      maxPerRoute: 20

---
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1

---
api.upload.path.notice: /home/ddetest/dde-upload/notice
api.upload.path.alarm: /home/ddetest/dde-upload/alarm

---
api.default.alarms: newAlarm.wav,assignAlarm.wav,assignedCancelAlarm.wav,completeAlarm.wav,cancelAlarm.wav
---
# Web socket
websocket.localhost: https://newdev-store.jrgtw.com
