---
spring:
  profiles: admin
  application.name: delivery-dispatch-admin
  mvc:
    favicon.enabled: false
  messages:
    cache-seconds: -1
    basename: classpath:/META-INF/messages/exceptions
                , classpath:/META-INF/messages/messages
    encoding: UTF-8
    #fallback-to-system-locale: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: true
  thymeleaf:
      cache : false
      prefix: classpath:/templates

management:
  context-path: /monitor

# was
server:
  port: 8182
  tomcat:
    uri-encoding: UTF-8
  jsp-servlet:
    init-parameters:
      development: true
  session:
    timeout: 3600

# concurrent
cntt.concurrent.enable: true
cntt.concurrent.threadCount: 8

# spring security disabled
security.basic.enabled: false
management.security.enabled: false

# mail service
#cntt.mail:
#  enable : true
#  sender : Do_not_reply@burgerking.co.kr
#  imageHeader : http://delivery.burgerking.co.kr/files/mail/mail_header.gif
#  imageLock : http://delivery.burgerking.co.kr/files/mail/img_lock.gif
#  tempPasswordMailTitle : TEST
#  tempPasswordMailHtmlPath : classpath:templates/mail/tempPasswordMail.html
#  tempPasswordMailSampleHtmlPath1 : classpath:templates/mail/tempPasswordMailSample1.html
#  tempPasswordMailSampleHtmlPath2 : classpath:templates/mail/tempPasswordMailSample2.html
#  tempPasswordMailSampleHtmlPath3 : classpath:templates/mail/tempPasswordMailSample3.html

cntt:
  underConstruction:
    redirectUrl: /caution
    ignoreIps: 127.0.0.1, 0:0:0:0:0:0:0:1, 123.111.91.3
    paramAdminPw: cbody
    active: true

---
spring:
  profiles: local

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
      scheme: http
      host: localhost
      port: 8091
      maxPerRoute: 20

---
spring:
  profiles: dev

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
      scheme: http
      host: localhost
      port: 8085
      maxPerRoute: 20

---
# Logger
cntt.monitor.enable: true
cntt.monitor.basepackage: kr.co.cntt.deliverydispatchadmin

---
api.token.serviceKey : testkey
api.token.secretKey : ATE6OLdQuouPbqyZ5qt1H++taImbDhqSPw53ClPT7+k=
api.token.expiration : 6000

---
api.tracker.key: sg9h6f6rg4lo1i3s255czh31v9zxc029

---
api.default.alarms: newAlarm.wav,assignAlarm.wav,assignedCancelAlarm.wav,completeAlarm.wav,cancelAlarm.wav

---
#메일 서버 정보 세팅
mail:
  host: smtp.gmail.com
  port: 465
  auth: true
  enable: true
  id: kaifalife@gmail.com
  pwd: trvqzugmzmflhbnb
