spring:
  application.name: delivery-dispatch-core
  mvc:
    locale: ko_KR
  messages:
    cache-seconds: -1
    basename: classpath:/META-INF/messages/kcp-validation
    encoding: UTF-8
  http:
      multipart:
        max-file-size: -1
        max-request-size: -1

smsSend:
  smsId : NANUM
  #callback : 15001111

---
spring:
  profiles: local
  mybatisEnvironmentId: development

  api:
    app:
      #appApiServer : https://dev.deliveryapp.co.kr/if/api/
      appApiServer : http://dev.deliveryapp.co.kr/if/api/
      accessToken : BKRIFDW020
      regIp : 123.111.91.3
      regPk : 123123
    gis:
      server: http://59.10.203.212:8080
    mvc:
      server : http://localhost:8080
  file:
    url : /files/
    savePath : D:/Web/BurgerkingFile/files/

---
spring:
  profiles: dev
  datasource:
    jmx-enabled: true
  mybatisEnvironmentId: development
  api:
    app:
      #appApiServer : http://dev.deliveryapp.co.kr:8081/if/api/
      appApiServer : http://dev.deliveryapp.co.kr/if/api/
      accessToken : BKRIFDW020
      regIp : 123.111.91.3
      regPk : 123123
    gis:
      server: http://59.10.203.212:8080
    mvc:
      server : http://localhost:8082

  file:
    url : /files/
    savePath : /home/burgerking/files/

---
spring:
  profiles: oper
  datasource:
    jmx-enabled: true
  mybatisEnvironmentId: production
  api:
    app:
      #appApiServer : http://dev.deliveryapp.co.kr:8081/if/api/
      appApiServer : https://deliveryapp.co.kr/if/api/
      #accessToken : BKRIFDW002
      accessToken : BKRIFDW001
      #regIp : 211.219.135.107
      #regIp : 59.10.203.198
      regIp : 121.162.141.135
      regPk : 123123
    gis:
      server: http://59.10.203.212:8080
    mvc:
      server : http://delivery.burgerking.co.kr
      #server : http://211.219.135.83
  file:
    url : /files/
    savePath : /web/images/files/
