---
spring:
  profiles: api
  application.name: delivery-dispatch-api
  mvc:
    locale: zh_TW
#    locale: zh_HK
#    locale: ko_KR
    favicon.enabled: false
  messages:
    cache-seconds: -1
    basename: classpath:/META-INF/messages/exceptions
    encoding: UTF-8
    #fallback-to-system-locale: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: true

# logging
logging:
# [DDE-TW-MAIN]
  config: classpath:logback-spring-tw.xml

# [DDE-HK-MAIN]
#  config: classpath:logback-spring-hk.xml

# datasource
datasource:
  deliveryDispatch:
    initialize: true
        initial-size: 20
        max-active: 100
        max-idle: 100
        min-idle: 20
        max-wait: 3000
        test-on-borrow: true
        validation-query: select 1
        test-while-idle: true
        min-evictable-idle-time-millis: 28700
        time-between-eviction-runs-millis: 60000
        driver-class-name: com.mysql.jdbc.Driver

#    [DDE-TW-MAIN]
    url: jdbc:mysql://dde-db.cs4wechlbmlc.ap-northeast-2.rds.amazonaws.com:3306/dde?useUnicode=true&characterEncoding=utf8
    username: nanum
    password: snaskzhf

#    [DDE-TW-TEST]
#    url: jdbc:mysql://delivery-dispatch-test-db.cktgcdnnnhc9.ap-northeast-2.rds.amazonaws.com:3306/dde?useUnicode=true&characterEncoding=utf8
#    username: nanum
#    password: snaskzhf

#    [DDE-HK-MAIN]
#    url: jdbc:mysql://192.168.100.73:3306/hkdb?useUnicode=true&characterEncoding=utf8
#    username: hkuser
#    password: hkuserpw!

# concurrent 설정
cntt.concurrent.enable: true
cntt.concurrent.threadCount: 8

# spring security and actuator management
security.basic.enabled: false
management.security.enabled: false

---
spring:
  profiles: local

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    scheme: http
    host: localhost
    port: 8091
    maxPerRoute: 20

# Logger 설정
cntt.monitor.enable: true
cntt.monitor.basepackage: kr.co.cntt.api

---
spring:
  profiles: dev

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    scheme: http
    host: localhost
    port: 8085
    maxPerRoute: 20

# Logger 설정
cntt.monitor.enable: true
cntt.monitor.basepackage: kr.co.cntt.api

---
spring:
  profiles: oper

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
#      [DDE-TW-MAIN]
      scheme: http
      host: ddetw-api.cntt.co.kr
      port: 8091
      maxPerRoute: 20

#      [DDE-TW-TEST]
#      scheme: http
#      host: dev-api.cntt.co.kr
#      port: 8091
#      maxPerRoute: 20

#      [DDE-HK-MAIN]
#      scheme: http
#      host: ddehk-api.cntt.co.kr
#      port: 8091
#      maxPerRoute: 20

    -
#      [DDE-TW-MAIN]
      scheme: https
      host: ddetw-api.cntt.co.kr
      port: 443
      maxPerRoute: 20

#      [DDE-TW-TEST]
#      scheme: https
#      host: dev-api.cntt.co.kr
#      port: 443
#      maxPerRoute: 20

#      [DDE-HK-MAIN]
#      scheme: https
#      host: ddehk-api.cntt.co.kr
#      port: 443
#      maxPerRoute: 20

# Logger 설정
cntt.monitor.enable: true
cntt.monitor.basepackage: kr.co.cntt.api

---
spring:
  profiles: api
server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8
  jsp-servlet:
    init-parameters:
      development: true
api.token.serviceKey : testkey
api.token.secretKey : ATE6OLdQuouPbqyZ5qt1H++taImbDhqSPw53ClPT7+k=
api.token.expiration : 6000

---
spring:
  redis:
#    [DDE-TW-MAIN]
    host: dde-tw-redis.dgc5ym.0001.apn2.cache.amazonaws.com
    port: 6379

#    [DDE-TW-TEST]
#    host: nanum-taiwan-redis.e6yhbk.0001.apn2.cache.amazonaws.com
#    port: 6379

#    [DDE-HK-MAIN]
#    host: 192.168.100.81
#    port: 6379

#    [DDE-KR-LOCAL]
#    host: 127.0.0.1
#    port: 6379

---
api.tracker.key: sg9h6f6rg4lo1i3s255czh31v9zxc029

---
#[DDE-TW-MAIN]
api.upload.path.notice: /home/nanum/dde-upload/notice
api.upload.path.alarm: /home/nanum/dde-upload/alarm

#[DDE-HK-MAIN]
#api.upload.path.notice: /root/dde-upload/notice
#api.upload.path.alarm: /root/dde-upload/alarm
