---
spring:
  profiles: api-connor
  profiles.include: api
  mvc:
    locale: zh_HK

# logging
logging:
  config: classpath:logback-spring-connor.xml

# datasource
datasource:
  deliveryDispatch:
    initialize: true
    initial-size: 10
    max-total: 50
    max-idle: 50
    min-idle: 10
    max-wait-millis: 3000
    test-on-borrow: true
    validation-query: select 1
    test-while-idle: true
    min-evictable-idle-time-millis: 28700
    time-between-eviction-runs-millis: 60000
    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://1.255.51.183:3306/devdb?useUnicode=true&characterEncoding=utf8
    username: devuser
    password: devuserpw!

---
spring:
  profiles: oper

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
      scheme: http
      host: dev-api.connor.local
      port: 8091
      maxPerRoute: 20

    -
      scheme: https
      host: dev-api.connor.local
      port: 443
      maxPerRoute: 20

---
spring:
  redis:
    host: 192.168.0.8
    port: 6379

---
api.upload.path.notice: /home/connor/websites/DDE/dde-upload/notice
api.upload.path.alarm: /home/connor/websites/DDE/dde-upload/alarm