---
spring:
  profiles: api-tw
  profiles.include: api
  mvc:
    locale: zh_TW

# logging
logging:
  config: classpath:logback-spring-tw.xml

# datasource
datasource:
  deliveryDispatch:
    initialize: true
    initial-size: 10
    max-total: 200
    max-idle: 100
    min-idle: 10
    max-wait-millis: 10000
    test-on-borrow: true
    validation-query: select 1
    test-while-idle: true
    min-evictable-idle-time-millis: 10000
    time-between-eviction-runs-millis: 18000
    driver-class-name: com.mysql.cj.jdbc.Driver

    #url: jdbc:mysql://192.168.100.73:3306/twdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    url: jdbc:mysql://10.156.32.3:3306/twdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: twuser
    password: twuserpw!

---
spring:
  profiles: oper

# rest template
cntt.restPool:
  enable: true
  pool-size: 200
  defaultMaxPerRoute: 200
  hosts:
    -
      scheme: http
#      host: ddetw-api.cntt.co.kr
#      port: 8091
      host: dde-api.jrgtw.com
      port: 80
      maxPerRoute: 200
    -
      scheme: https
#      host: ddetw-api.cntt.co.kr
      host: dde-api.jrgtw.com
      port: 443
      maxPerRoute: 200

---
spring:
  redis:
#    host: 192.168.100.81
    host: 10.150.16.4
    port: 6379
    database: 0

---
#api.upload.path.notice: /root/dde-upload/notice
#api.upload.path.alarm: /root/dde-upload/alarm
api.upload.path.notice: /home/ddetw/dde-upload/notice
api.upload.path.alarm: /home/ddetw/dde-upload/alarm
