---
spring:
  profiles: api
  application.name: delivery-dispatch-api
  mvc:
    favicon.enabled: false
  messages:
    cache-seconds: -1
    basename: classpath:/META-INF/messages/exceptions
    encoding: UTF-8
    #fallback-to-system-locale: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: true

# concurrent 설정
cntt.concurrent.enable: true
cntt.concurrent.threadCount: 8

# spring security and actuator management
security.basic.enabled: false
management.security.enabled: false

---
spring:
  profiles: local

# rest template
cntt.restPool:
  enable: true
  pool-size: 200
  defaultMaxPerRoute: 200
  hosts:
    scheme: http
    host: localhost
    port: 8091
    maxPerRoute: 200

---
spring:
  profiles: dev

# rest template
cntt.restPool:
  enable: true
  pool-size: 200
  defaultMaxPerRoute: 200
  hosts:
    scheme: http
    host: localhost
    port: 8085
    maxPerRoute: 200

---
# Logger 설정
cntt.monitor.enable: true
cntt.monitor.basepackage: kr.co.cntt.api

---
spring:
  profiles: api
server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8
  jsp-servlet:
    init-parameters:
      development: true
api.token.serviceKey : testkey
api.token.secretKey : ATE6OLdQuouPbqyZ5qt1H++taImbDhqSPw53ClPT7+k=
api.token.expiration : 6000

---
api.tracker.key: sg9h6f6rg4lo1i3s255czh31v9zxc029