---
spring:
  profiles: api
  application.name: delivery-dispatch-api
  mvc:
    locale: zh_TW
    favicon.enabled: false
  messages:
    cache-seconds: -1
    basename: classpath:/META-INF/messages/exceptions
    encoding: UTF-8
    #fallback-to-system-locale: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: true

# logging
logging:
  config: classpath:logback-spring.xml

# datasource
datasource:
  deliveryDispatch:
    initialize: true
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dde-db.cs4wechlbmlc.ap-northeast-2.rds.amazonaws.com:3306/dde?useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://delivery-dispatch-test-db.cktgcdnnnhc9.ap-northeast-2.rds.amazonaws.com:3306/dde?useUnicode=true&characterEncoding=utf8
    username: nanum
    password: snaskzhf
    initial-size: 10
    max-active: 10
    max-idle: 10
    min-idle: 10
    max-wait: 3000
    test-on-borrow: true
    #validation-query: select 1

# concurrent 설정
cntt.concurrent.enable: true
cntt.concurrent.threadCount: 8

# spring security and actuator management
security.basic.enabled: false
management.security.enabled: false

---
spring:
  profiles: local

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    scheme: http
    host: localhost
    port: 8091
    maxPerRoute: 20

api.server : http://localhost:8091
# Logger 설정
cntt.monitor.enable: true
cntt.monitor.basepackage: kr.co.cntt.api

---
spring:
  profiles: dev

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    scheme: http
    host: localhost
    port: 8085
    maxPerRoute: 20

api.server : http://localhost:8084
# Logger 설정
cntt.monitor.enable: true
cntt.monitor.basepackage: kr.co.cntt.api

---
spring:
  profiles: oper

# rest template
cntt.restPool:
  enable: true
  pool-size: 20
  defaultMaxPerRoute: 20
  hosts:
    -
      scheme: http
      host: ddetw-api.cntt.co.kr
      port: 8091
      maxPerRoute: 20

      #scheme: http
      #host: dev-api.cntt.co.kr
      #port: 8091
      #maxPerRoute: 20

      #scheme: http
      #host: oper.co.kr
      #port: 8081
      #maxPerRoute: 20
    -
      scheme: https
      host: ddetw-api.cntt.co.kr
      port: 443
      maxPerRoute: 20

      #scheme: https
      #host: dev-api.cntt.co.kr
      #port: 443
      #maxPerRoute: 20

api.server : https://ddetw-api.cntt.co.kr
#api.server : https://dev-api.cntt.co.kr
#api.server : https://oper.kr:9443

# Logger 설정
cntt.monitor.enable: true
cntt.monitor.basepackage: kr.co.cntt.api

---
spring:
  profiles: api
server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8
  jsp-servlet:
    init-parameters:
      development: true
api.token.serviceKey : testkey
api.token.secretKey : ATE6OLdQuouPbqyZ5qt1H++taImbDhqSPw53ClPT7+k=
api.token.expiration : 6000

---
spring:
  redis:
    host: dde-tw-redis.dgc5ym.0001.apn2.cache.amazonaws.com
#    host: nanum-taiwan-redis.e6yhbk.0001.apn2.cache.amazonaws.com
#    host: 127.0.0.1
    port: 6379

---
api.tracker.key: sg9h6f6rg4lo1i3s255czh31v9zxc029

---
api.upload.path.notice: /home/nanum/dde-upload/notice
api.upload.path.alarm: /home/nanum/dde-upload/alarm