spring:
  application.name: delivery-dispatch-core

---
spring:
  profiles: local
  mybatisEnvironmentId: development
  file:
      url : /files/
      savePath : D:/Web/delivery-dispatch/files/

---
spring:
  profiles: dev
  datasource:
    jmx-enabled: true
  mybatisEnvironmentId: development
  file:
      url : /files/
      savePath : /home/delivery-dispatch/files/

---
spring:
  profiles: oper
  datasource:
    jmx-enabled: true
  mybatisEnvironmentId: production
  file:
      url : /files/
      savePath : /home/delivery-dispatch/files/