spring:
  application.name: delivery-dispatch-core

---
spring:
  profiles: local
  mybatisEnvironmentId: development

---
spring:
  profiles: dev
  datasource:
    jmx-enabled: true
  mybatisEnvironmentId: development

---
spring:
  profiles: oper
  datasource:
    jmx-enabled: true
  mybatisEnvironmentId: production
